#ifndef _MAIN_FILETABLE_H
#define _MAIN_FILETABLE_H

#include "common.h"

#define FS_BLOCK_SIZE    0x100 /** Units in which file size is measured in THE file table. */
#define FS_SECTOR_SIZE   0x800 /** Size of a CD sector (2048 bytes). */
#define FS_SECTOR_SHIFT  11    /** For dividing by `FS_SECTOR_SIZE`. */
#define FS_NAME_CHAR_MAX 8     /** Maximum amount of characters in a file name (excluding extension and path). */
#define FS_INVALID_TYPE  0x0F  /** Unspecified file type (or empty extension). */

/** @brief Enum containing the index of each game asset file for use with FS functions.
 *
 * @note The .inc file is generated by `silentassets`.
 */
typedef enum _FsFile
{
#if VERSION_IS(USA)
    #include "fileenum.h.USA.inc"
#elif VERSION_IS(JAP0) || VERSION_IS(JAP1) || VERSION_IS(JAP2)
    #include "fileenum.h.JAP0.inc"
#endif
    FS_FILE_COUNT /** Number of files in `g_FileTable`. 2074 in USA/JAP0. */
} e_FsFile;

typedef enum _FileType
{
    FileType_Tim = 0,
    FileType_Vab = 1,
    FileType_Bin = 2,
    FileType_Dms = 3,
    FileType_Anm = 4,
    FileType_Plm = 5,
    FileType_Ipd = 6,
    FileType_Ilm = 7,
    FileType_Tmd = 8,
    FileType_Dat = 9,
    FileType_Kdt = 10,
    FileType_Cmp = 11
} e_FileType;

/** @brief Entry in the file table.
 *
 * Contains the metadata of a single file in file table (`g_FileTable`):
 * its name, size and location on the CD.
 *
 * The file name is stored as 8 6-bit characters represented as two 24-bit bitfields:
 * `name4567` and `name4567`. The 6-bit character value maps to ASCII character range `[0x20, 0x5F]`.
 * The name does not contain the path or extension.
 *
 * The path and extension are stored as 4-bit indices of the path string in `g_FilePaths` and of
 * the extension string in `g_FileExts`, respectively. This limits the amount of paths and extensions
 * to 16 each, with one representing an empty extension.
 */
typedef struct _FileInfo
{
    /* 0x0+0  */ u32 startSector : 19; /** Index of CD sector where file starts. */
    /* 0x0+19 */ u32 blockCount  : 12; /** Size of file in 256-byte blocks. */
    /* 0x4+0  */ u32 pathIdx     : 4;  /** Index of path to file in `g_FilePaths`. */
    /* 0x4+4  */ u32 name0123    : 24; /** First four 6-bit characters of file name. */
    /* 0x8+0  */ u32 name4567    : 24; /** Second four 6-bit characters of file name. */
    /* 0x8+24 */ u32 type        : 4;  /** `e_FileType` | File type (and index of extension in `g_FileExts`). */
} s_FileInfo;
STATIC_ASSERT_SIZEOF(s_FileInfo, 12);

/** @brief File information table.
 *
 * The file table is the index to the game's two data archives:
 * the files `SILENT.` and `HILL.` on the CD. It contains metadata of every file
 * in those archives, such as the name, size, file type and where the file is on the CD.
 *
 * @note Not `const` because it has to end up in .data. Was also like that in the header
 * found in one of the prototypes.
 *
 * @note The .inc file is generated by `silentassets`.
 */
extern s_FileInfo g_FileTable[];

/** @brief Array of file path strings.
 *
 * All possible path strings occuring in the data archives.
 * This is referenced by index (`pathIdx`) in each file table entry.
 *
 * In SLUS_007.07 there are 11 possible paths. They are all one subfolder deep
 * and have starting and trailing path separators (backslashes).
 *
 * @note Not `const char*` because it has to end up in .data/.sdata. Was also `char*` in the header
 * found in one of the prototypes.
 */
extern char* g_FilePaths[];

/** @brief Array of file extension strings.
 *
 * All possible file extensions occuring in the data archives.
 * This is referenced by index (`type`) in each file table entry.
 *
 * In SLUS_007.07 there are 12 possible extensions. They all start with a dot
 * and are 3 characters long (`.XXX`).
 *
 * @note Not `const char*` because it has to end up in .data/.sdata. Was also `char*` in the header
 * found in one of the prototypes.
 */
extern char* g_FileExts[];

/** @brief Array of starting sector numbers for the first 9 \XA\ files in the file table (2044 - 2052).
 * These files seem to contain dialog and music. Array starts and ends with 0s.
 */
extern u32 g_FileXaLoc[];

#ifdef SH_PC_PORT
/** @brief Game disc region. The PC port is a single executable that selects the
 * file table / XA offsets at runtime from the disc it loads (US is canonical). */
typedef enum _GameRegion
{
    Region_USA = 0,
    Region_EUR = 1, /** PAL (SLES-01514). */
    Region_JPN = 2, /** NTSC-J (SLPM-86192). Rev 1/Rev 2 (JAP1/JAP2) discs share
                     *  the file table + overlay link base; the first print
                     *  (JAP0) differs and is detected but not yet supported. */
} e_GameRegion;

extern e_GameRegion g_GameRegion;

/** @brief Populate g_FileTable and g_FileXaLoc for the detected disc region.
 * g_FileTable keeps the US-canonical shape/indices so every FILE_* enum
 * reference resolves unchanged; for EUR the actual disc sectors are filled in
 * by matching each US file to its same-named EUR entry. Also applies the
 * config `language` redirects (VIN map overlays -> VIN2..VIN5, TIPS letter). */
void Fs_InitFileTableForRegion(e_GameRegion region);

/** @brief Locate an EUR-only file (no US-canonical slot, e.g. VIN/ITEM_GER.BIN)
 * in the compiled EUR table. `name8` = bare name, no extension. Returns 1 on hit. */
int Fs_EurFileLookup(const char* name8, s32 pathIdx, s32 type, u32* outSector, u32* outBlocks);

/** @brief Fan-disc support, any region: overwrite g_FileTable sectors/sizes (and
 * the audio + XA offset tables) from the mounted disc's OWN file table, matched
 * by name. A fan re-translation can rebuild the CD, shifting every sector;
 * reading the disc's table is the only way to know the true layout. `disc` points
 * at the raw 12-byte file-table entries read out of the disc executable, `count` =
 * how many. On PAL the match runs through the EUR name/path shape (including the
 * active language redirect) since g_FileTable stays US-canonical.
 * No-op (returns 0) when the disc matches the baked table for its region. */
s32 Fs_RemapFromDiscTable(const s_FileInfo* disc, s32 count);

/** @brief (Re)bind the VIN map-overlay + TIPS entries to the configured
 * language's EUR files. Idempotent — the title-screen options menu re-runs
 * it when the language changes. No-op outside Region_EUR. */
void Fs_ApplyLanguageRedirects(void);

/** @brief The file's REAL on-disc directory + name for the active region, when
 * the US-canonical g_FileTable entry does not name it.
 *
 * g_FileTable is kept in US-canonical shape so the FILE_* enum indices resolve
 * unchanged, but on PAL the localized assets live under different names/dirs
 * (VIN/MAPx_S0z -> VIN2..VIN5/MAPx_S<lang>z, TIM/TIPS_Exy -> TIM/TIPS_<L>xy).
 * Anything that addresses a file BY NAME on disk — the loose-file override
 * probe — needs the real name, not the canonical one.
 *
 * Returns 1 and fills `*outDir` (bare directory, no separators; points at
 * static storage) and `outName` (name + extension, needs FS_NAME_CHAR_MAX + 5
 * bytes) only when they differ from the canonical entry. Returns 0 otherwise,
 * which is every file on USA/JPN and every file on an English PAL disc. */
int Fs_GetRegionFilePath(s32 fileIdx, const char** outDir, char* outName);
#endif

/** @brief Decrypts an encrypted overlay.
 *
 * The overlays in the `1ST` folder in the data archives are encrypted.
 * Overlays in the `VIN` folder don't appear to be.
 * This function decrypts data dword-by-dword, so `size` presumably must be
 * divible by 4 to work properly.
 *
 * @param dest Destination buffer. Must be `size` long.
 * @param src Encrypted overlay data.
 * @param size The number of bytes to decrypt.
 */
void Fs_DecryptOverlay(s32* dest, const s32* src, s32 size);

/** @brief Gets the size of a file in the file table.
 *
 * Takes a file table entry index (`fileIdx`) and returns the size of that file,
 * obtained from its file table entry.
 *
 * @param fileIdx The index of the file entry to look up.
 * @return The size of the specified file entry in bytes.
 */
s32 Fs_GetFileSize(s32 fileIdx);

/** @brief Gets the full name of a file in the file table.
 *
 * Takes a file table entry index (`fileIdx`) and returns the name of that file (with extension)
 * into `outName`.
 * The name is decoded from its file table representation into proper ASCII and is null terminated.
 *
 * @note `outName` must be at least 13 bytes long to fit the longest possible name in 8.3 format.
 * There are no size checks.
 *
 * @param[out] outName Buffer where the decoded file name will be stored.
 * @param[in] fileIdx Index of the file in the file table.
 */
void Fs_GetFileName(char* outName, s32 fileIdx);

/** @brief Gets the name from a file table entry.
 *
 * Returns the name (with extension) in the file table entry `fentry`.
 * The name is decoded from its file table representation into proper ASCII and is null terminated.
 *
 * @note `outName` must be at least 13 bytes long to fit the longest possible name in 8.3 format.
 * There are no size checks.
 *
 * @param[out] outName Buffer where the decoded file name will be stored.
 * @param[in] fileEntry Pointer to the file table entry from which to decode the name.
 */
void Fs_GetFileInfoName(char* outName, const s_FileInfo* const fileEntry);

/** @brief Encodes a file name into 6-bit file table representation.
 *
 * Takes an ASCII file name and encodes it into the 6-bits per character format
 * used by the file table.
 * The name is stored in two 32-bit integers pointed to by `outName0123` and `outName4567`,
 * corresponding to the `s_FileInfo` fields of the same name.
 *
 * Example of the file name encoding:
 *   For string like 'HERO':
 *   i0: 'H' - 0x20 << 0       = 0x28     (0000 0000 0000 0000 0010 1000)
 *       -> 0x28 | 0x0         = 0x28     (0000 0000 0000 0000 0010 1000)
 *   i1: 'E' - 0x20 << 6       = 0x940    (0000 0000 0000 1001 0100 0000)
 *       -> 0x28 | 0x940       = 0x968    (0000 0000 0000 1001 0110 1000)
 *   i2: 'R' - 0x20 << 12      = 0x32000  (0000 0011 0010 0000 0000 0000)
 *       -> 0x968 | 0x32000    = 0x32968  (0000 0011 0010 1001 0110 1000)
 *   i3: 'O' - 0x20 << 18      = 0xBC0000 (1011 1100 0000 0000 0000 0000)
 *       -> 0x32968 | 0xBC0000 = 0xBF2968 (1011 1111 0010 1001 0110 1000)
 *
 * @param[out] outName0123 Pointer to the integer where the first part of the
 * encoded name will be stored.
 * @param[out] outName4567 Pointer to the integer where the second part of the
 * encoded name will be stored.
 * @param[in] srcName The file name string to encode.
 */
void Fs_EncodeFileName(s32* outName0123, s32* outName4567, const char* srcName);

/** @brief Gets the size of a file rounded up to CD sector size.
 *
 * Takes an index in the file table and returns that file's size in bytes, rounded up to
 * CD sector size (2048 bytes).
 *
 * @param fileIdx The index of the file entry to look up.
 * @return The size of the specified file entry in bytes rounded up to CD sector boundary.
 */
s32 Fs_GetFileSectorAlignedSize(s32 fileIdx);

/** @brief Finds a file of the specified type in the file table.
 *
 * Starts a linear search from the file table index `startIdx`,
 * going forwards if `direction` is positive, or backwards if it's negative.
 * Returns the index of the first file it encounters whose `type` field is `fileType`,
 * or -1 if it reaches the end of the table without finding anything.
 *
 * @param fileType The file type to search for.
 * @param startIdx The table index from which to start the search.
 * @param dir The direction of the search: positive for incrementing,
 * negative for decrementing.
 * @return The index of the first matching file entry, or -1 if not found.
 */
s32 Fs_FindNextFileOfType(s32 fileType, s32 startIdx, s32 dir);

/** @brief Finds a file with the specified name and type in the file table.
 *
 * Starts a linear search from the file table index `startIdx` and moves forward.
 * Returns the index of the first file it encounters whose `type` field is `fileType`
 * and whose name is the same as `name`, or -1 if it reaches the end of the table
 * without finding anything.
 *
 * @param name The file name to search for.
 * @param fileType The file type ID to match.
 * @param startIdx The offset from which to start the search.
 * @return The index of the matching file entry, or -1 if not found.
 */
s32 Fs_FindNextFile(const char* name, s32 fileType, s32 startIdx);

#endif
